apiVersion: v2
name: todo-chatbot
description: A Helm chart for Todo Chatbot application with AI assistant
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - todo
  - chatbot
  - nextjs
  - fastapi
maintainers:
  - name: Todo Team
