apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.recurringService.name }}
  labels:
    app: {{ .Values.recurringService.name }}
spec:
  replicas: {{ .Values.recurringService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.recurringService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.recurringService.name }}
      {{- if .Values.dapr.enabled }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: {{ .Values.recurringService.dapr.appId }}
        dapr.io/app-port: "{{ .Values.recurringService.dapr.appPort }}"
        dapr.io/log-level: {{ .Values.dapr.logLevel }}
      {{- end }}
    spec:
      containers:
      - name: {{ .Values.recurringService.name }}
        image: "{{ .Values.recurringService.image.repository }}:{{ .Values.recurringService.image.tag }}"
        imagePullPolicy: {{ .Values.recurringService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.recurringService.service.targetPort }}
          name: http
        env:
        {{- range .Values.recurringService.env }}
        - name: {{ .name }}
          {{- if .value }}
          value: {{ .value | quote }}
          {{- else if .valueFrom }}
          valueFrom:
            {{- toYaml .valueFrom | nindent 12 }}
          {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.recurringService.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.recurringService.name }}
  labels:
    app: {{ .Values.recurringService.name }}
spec:
  type: {{ .Values.recurringService.service.type }}
  ports:
  - port: {{ .Values.recurringService.service.port }}
    targetPort: {{ .Values.recurringService.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.recurringService.name }}
